export enum State {
  ANDHRA_PRADESH = 'ANDHRA_PRADESH',

  ARUNACHAL_PRADESH = 'ARUNACHAL_PRADESH',

  ASSAM = 'ASSAM',

  BIHAR = 'BIHAR',

  CHHATTISGARH = 'CHHATTISGARH',

  GOA = 'GOA',

  GUJARAT = 'GUJARAT',

  HARYANA = 'HARYANA',

  HIMACHAL_PRADESH = 'HIMACHAL_PRADESH',

  JAMMU_AND_KASHMIR = 'JAMMU_AND_KASHMIR',

  JHARKHAND = 'JHARKHAND',

  KARNATAKA = 'KARNATAKA',

  KERALA = 'KERALA',

  MADHYA_PRADESH = 'MADHYA_PRADESH',

  MAHARASHTRA = 'MAHARASHTRA',

  MANIPUR = 'MANIPUR',

  MEGHALAYA = 'MEGHALAYA',

  MIZORAM = 'MIZORAM',

  NAGALAND = 'NAGALAND',

  ODISHA = 'ODISHA',

  PUNJAB = 'PUNJAB',

  RAJASTHAN = 'RAJASTHAN',

  SIKKIM = 'SIKKIM',

  TAMIL_NADU = 'TAMIL_NADU',

  TELANGANA = 'TELANGANA',

  TRIPURA = 'TRIPURA',

  UTTARAKHAND = 'UTTARAKHAND',

  UTTAR_PRADESH = 'UTTAR_PRADESH',

  WEST_BENGAL = 'WEST_BENGAL',

  ANDAMAN_AND_NICOBAR_ISLANDS = 'ANDAMAN_AND_NICOBAR_ISLANDS',

  CHANDIGARH = 'CHANDIGARH',

  DADRA_AND_NAGAR_HAVELI = 'DADRA_AND_NAGAR_HAVELI',

  DAMAN_AND_DIU = 'DAMAN_AND_DIU',

  DELHI = 'DELHI',

  LAKSHADWEEP = 'LAKSHADWEEP',

  PUDUCHERRY = 'PUDUCHERRY',
}
